# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  decent-sampler-dynamic = {
    pname = "decent-sampler-dynamic";
    version = "1.14.1";
    src = fetchurl {
      url = "https://www.dropbox.com/scl/fi/bsprf1ak5i2dh37zpq91y/Decent_Sampler-1.14.1-Linux-Dynamic-x86_64.tar.gz?rlkey=wr1s23a51mqnvtvinlh8qyr3t&st=0qk15q4u&dl=0";
      name = "Decent_Sampler-1.14.1-Linux-Dynamic-x86_64.tar.gz";
      sha256 = "sha256-wVCxFzDxNtxl0x+N8Nu3iZDEg/iEuVX3z4t051DP55E=";
    };
  };
}
