# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wl_shimeji = {
    pname = "wl_shimeji";
    version = "9ad350f23d2121a4717f6215b32221d77543e0ca";
    src = fetchFromGitHub {
      owner = "CluelessCatBurger";
      repo = "wl_shimeji";
      rev = "9ad350f23d2121a4717f6215b32221d77543e0ca";
      fetchSubmodules = true;
      deepClone = true;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ME/Mbasi6DfJ0N9OX3imy9VPrZhgHwBn271+TbUDT3M=";
    };
    date = "2025-08-08";
  };
}
