# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hyprcursor = {
    pname = "hyprcursor";
    version = "44e91d467bdad8dcf8bbd2ac7cf49972540980a5";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprcursor";
      rev = "44e91d467bdad8dcf8bbd2ac7cf49972540980a5";
      fetchSubmodules = false;
      sha256 = "sha256-lIqabfBY7z/OANxHoPeIrDJrFyYy9jAM4GQLzZ2feCM=";
    };
    date = "2025-07-31";
  };
  hyprlock = {
    pname = "hyprlock";
    version = "98b86752fe4867bd14ef96a92ea788229af93130";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprlock";
      rev = "98b86752fe4867bd14ef96a92ea788229af93130";
      fetchSubmodules = false;
      sha256 = "sha256-Et1jNDB2d3e0b4okIKuyAMktECS+5hk+vMAA7X598ao=";
    };
    date = "2025-10-28";
  };
  swww = {
    pname = "swww";
    version = "432b7135af0bb34e4b0e55edf76ff516937bc7b0";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "432b7135af0bb34e4b0e55edf76ff516937bc7b0";
      fetchSubmodules = false;
      sha256 = "sha256-pX6fJrlNXe1W5ZO9nC9ikN1zoAcHDqErLS7EnglD33o=";
    };
  };
  wallust = {
    pname = "wallust";
    version = "0a0e7c0ca83a4528f1e6e9f35ecce7a263847438";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust.git";
      rev = "0a0e7c0ca83a4528f1e6e9f35ecce7a263847438";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-2FLuAgANlLnepIcZknQB3gNE4M1U/xsr+pO9TJHHmyc=";
    };
    date = "2025-07-21";
  };
}
