# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hyprcursor = {
    pname = "hyprcursor";
    version = "44e91d467bdad8dcf8bbd2ac7cf49972540980a5";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprcursor";
      rev = "44e91d467bdad8dcf8bbd2ac7cf49972540980a5";
      fetchSubmodules = false;
      sha256 = "sha256-lIqabfBY7z/OANxHoPeIrDJrFyYy9jAM4GQLzZ2feCM=";
    };
    date = "2025-07-31";
  };
  hyprlock = {
    pname = "hyprlock";
    version = "ef3017f5efba0db0960474a74d519a19816057fb";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprlock";
      rev = "ef3017f5efba0db0960474a74d519a19816057fb";
      fetchSubmodules = false;
      sha256 = "sha256-Vk23viKuhcP5O5uIXXZopDZgd/TT5FgsfZ3ZoRp8k58=";
    };
    date = "2025-12-20";
  };
  swww = {
    pname = "swww";
    version = "432b7135af0bb34e4b0e55edf76ff516937bc7b0";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "432b7135af0bb34e4b0e55edf76ff516937bc7b0";
      fetchSubmodules = false;
      sha256 = "sha256-pX6fJrlNXe1W5ZO9nC9ikN1zoAcHDqErLS7EnglD33o=";
    };
  };
  wallust = {
    pname = "wallust";
    version = "bb408366ee3b1dc6b2841c9063d29e4f7bbd5e12";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust.git";
      rev = "bb408366ee3b1dc6b2841c9063d29e4f7bbd5e12";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-eD/KlhNN6UFDh9IJxGsE42mjhIEyb0FNXL3n7DDg/pY=";
    };
    date = "2025-12-07";
  };
}
