# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  sfizz-lv2 = {
    pname = "sfizz-lv2";
    version = "5e0be2e6ab61ed7e01619a7c9f2f8851405c8c31";
    src = fetchgit {
      url = "https://github.com/sfztools/sfizz-ui.git";
      rev = "5e0be2e6ab61ed7e01619a7c9f2f8851405c8c31";
      fetchSubmodules = true;
      deepClone = true;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-laHf4ryGKXFHvx/Gw/RQ0a5z45SRzQyoDr8qfye+etQ=";
    };
    date = "2025-03-19";
  };
}
